### ISSUE TITLE
No requirements.txt to use 

### ISSUE THREAD

**Issue by arduinoprojectfiles** [Rishit-katiyar/Aerospace_Task_and_Motion_Planning#1]
The project seems to be missing a "requirements.txt" file. This file typically lists all the external libraries or dependencies needed to run the code. Without it, anyone trying to set up the project would need to manually install the required libraries, which can be time-consuming and error-prone.

**Comment by Rishit-katiyar** [comment]
i have now added the requirements,https://github.com/Rishit-katiyar/Aerospace_Task_and_Motion_Planning/blob/efe503b9fce777481d5f0853146e72fb58112116/requirements.txt
